criação da entidade costumer
rodrigovsousa/bilhares-sobradinho pull request #1
Opened 2023-07-07 23:20 UTC by gabrielaodc

2023-07-07 23:31 UTC, rodrigovsousa requested changes

2023-07-07 23:31 UTC, rodrigovsousa commented on src/main/java/com/example/bilharessobradinho/domain/Costumer.java
> +        return Objects.equals(id, costumer.id) && Objects.equals(name, costumer.name) && Objects.equals(lastName, costumer.lastName) && Objects.equals(cpf, costumer.cpf) && Objects.equals(email, cost
Observar a linha na vertical da sua IDE e não deixar o código passar dela.
Pode identar e quebrar a linha 111 nos "&&" que fica melhor, ok?

2023-07-07 23:31 UTC, rodrigovsousa commented on src/main/java/com/example/bilharessobradinho/domain/Costumer.java
> +    @Column(name = "email", nullable = false, unique = true)
o "@Email" e "@CPF" por convenção ficar acima do @Column

2023-07-08 00:09 UTC, gabrielaodc commented on src/main/java/com/example/bilharessobradinho/domain/Costumer.java
> +    @Column(name = "email", nullable = false, unique = true)
Resolvido!

2023-07-08 00:10 UTC, gabrielaodc commented on src/main/java/com/example/bilharessobradinho/domain/Costumer.java
> +        return Objects.equals(id, costumer.id) && Objects.equals(name, costumer.name) && Objects.equals(lastName, costumer.lastName) && Objects.equals(cpf, costumer.cpf) && Objects.equals(email, cost
Resolvido!

2023-07-08 00:11 UTC, merged